import type { HookEvent, ResolvedConfig } from '../types.js';
import { getAllRules } from '../engine/registry.js';
import { serializeConfig } from '../config/compile.js';
import { generatePreamble } from './templates/preamble.js';
import { getTemplate } from './templates/index.js';

/**
 * Generate a self-contained hook script that works without VGuard installed.
 *
 * All rule logic is inlined via the template system. The bundled script embeds
 * the resolved config and rule check code inline, so it can run with just
 * Node.js — no npm dependencies needed.
 */
export function bundleHookScript(event: HookEvent, config: ResolvedConfig): string {
  const serialized = serializeConfig(config);
  const allRules = getAllRules();

  // Collect enabled rules for this event
  const enabledRules: Array<{
    id: string;
    severity: string;
    options: Record<string, unknown>;
  }> = [];

  for (const [ruleId, ruleConfig] of config.rules) {
    if (!ruleConfig.enabled) continue;
    const rule = allRules.get(ruleId);
    if (!rule) continue;
    if (!rule.events.includes(event)) continue;
    enabledRules.push({
      id: ruleId,
      severity: ruleConfig.severity,
      options: ruleConfig.options,
    });
  }

  // Generate inline checks for each rule
  const ruleChecks = enabledRules
    .map((r) => {
      const template = getTemplate(r.id);
      if (!template) {
        return `// ${r.id} — no inline template available`;
      }
      return `try {
${template({ ruleId: r.id, severity: r.severity, options: r.options, event })}
} catch (_e) { /* fail-open */ }`;
    })
    .join('\n\n');

  // Generate the output handler based on event type
  const outputHandler = generateOutputHandler(event);

  return `#!/usr/bin/env node
// VGuard Ejected Hook — ${event}
// Generated by \`vguard eject\`. This script is self-contained.
// It does NOT require VGuard to be installed.
//
// Rules: ${enabledRules.map((r) => r.id).join(', ') || 'none'}
// Generated: ${new Date().toISOString()}

${generatePreamble()}
// Embedded resolved config
const CONFIG = ${JSON.stringify(serialized, null, 2)};

// ─── Rule Checks ────────────────────────────────────────────────────────────
${ruleChecks}

// ─── Output ─────────────────────────────────────────────────────────────────
${outputHandler}
`;
}

/**
 * Generate the output handler for a given event type.
 * Mirrors the logic from src/engine/output.ts.
 */
function generateOutputHandler(event: HookEvent): string {
  if (event === 'PreToolUse') {
    return `// PreToolUse: block on first blocking issue, or warn
const blocking = issues.find(i => i.severity === 'block');
if (blocking) {
  process.stderr.write('\\nBLOCKED by VGuard [' + blocking.ruleId + ']\\n\\n' + blocking.message + '\\n');
  if (blocking.fix) process.stderr.write('\\nFix: ' + blocking.fix + '\\n');
  process.exit(2);
}
const warns = issues.filter(i => i.severity === 'warn');
if (warns.length > 0) {
  const msg = warns.map(w => '[' + w.ruleId + '] ' + w.message).join('\\n');
  process.stdout.write(JSON.stringify({ continue: true, systemMessage: 'VGuard: ' + msg }));
}
process.exit(0);`;
  }

  if (event === 'PostToolUse') {
    return `// PostToolUse: feedback only
const allIssues = issues.filter(i => i.severity !== 'pass');
if (allIssues.length > 0) {
  const msg = allIssues.map(r => '[' + r.ruleId + '] ' + r.message).join('\\n');
  process.stdout.write(JSON.stringify({ decision: 'block', reason: 'VGuard feedback:\\n' + msg }));
}
process.exit(0);`;
  }

  // Stop event
  return `// Stop: informational summary
const msgs = issues.filter(i => i.severity !== 'pass').map(r => '  - ' + (r.message || r.ruleId)).join('\\n');
if (msgs) {
  process.stderr.write('\\nVGuard session summary:\\n' + msgs + '\\n');
}
process.exit(0);`;
}
